const iranStates = [
  { label: "آذربایجان شرقی", value: "az-sharghi" },
  { label: "آذربایجان غربی", value: "az-gharbi" },
  { label: "اردبیل", value: "ardabil" },
  { label: "اصفهان", value: "isfahan" },
  { label: "البرز", value: "alborz" },
  { label: "ایلام", value: "ilam" },
  { label: "بوشهر", value: "bushehr" },
  { label: "تهران", value: "tehran" },
  { label: "چهارمحال و بختیاری", value: "chaharmahal-bakhtiari" },
  { label: "خراسان جنوبی", value: "khorasan-jonubi" },
  { label: "خراسان رضوی", value: "khorasan-razavi" },
  { label: "خراسان شمالی", value: "khorasan-shomali" },
  { label: "خوزستان", value: "khuzestan" },
  { label: "زنجان", value: "zanjan" },
  { label: "سمنان", value: "semnan" },
  { label: "سیستان و بلوچستان", value: "sistan-baluchestan" },
  { label: "فارس", value: "fars" },
  { label: "قزوین", value: "qazvin" },
  { label: "قم", value: "qom" },
  { label: "کردستان", value: "kordestan" },
  { label: "کرمان", value: "kerman" },
  { label: "کرمانشاه", value: "kermanshah" },
  { label: "کهگیلویه و بویراحمد", value: "kohgiluyeh-boyerahmad" },
  { label: "گلستان", value: "golestan" },
  { label: "گیلان", value: "gilan" },
  { label: "لرستان", value: "lorestan" },
  { label: "مازندران", value: "mazandaran" },
  { label: "مرکزی", value: "markazi" },
  { label: "هرمزگان", value: "hormozgan" },
  { label: "همدان", value: "hamedan" },
  { label: "یزد", value: "yazd" },
];


export default iranStates